### PR TITLE
Supports bots and fixes searching > 100 messages

### PR DESCRIPTION
**Pull request by jarrah31**
First of all, apologies for my poor Python, this is my first go at coding with it!

I wanted to support the 'bot' group type so that I could delete a 39,000 message group used for Home Assistant messages, and I also wanted to search for more than 100 messages at a time, but soon found that the Pyrogram raw search wouldn't allow this (see https://github.com/pyrogram/pyrogram/issues/637).

I therefore had a go at fixing both of these issues, resulting in this pull request. I'm surprised I managed to make it all work! 

It now lists bot, group, and supergroups, and caters for the fact that bots don't use 'title'. There are probably more elegant ways to my for loops, but they do the job. 

One change that might be a problem is that I removed the `from_id` element from search because it wouldn't find any bot messages or delete all messages within a group I owned. If you aren't the group owner, would it still only delete your messages anyway? I can't test this unfortunately as I don't have any other groups. 

I re-purposed the `search_limit` variable so that a user could specify how many messages to delete at once for testing purposes. You may only want to delete 50 messages at first to check it works as expected, rather than going full on and deleting everything first run.

The old `search_limit` variable was changed to `search_chunk_size` as discussed and suggested by @hannesveit [here](https://github.com/gurland/telegram-delete-all-messages/issues/31#issuecomment-797493545)

I think that covers all the changes I made. Please go easy on me as this is not only my first Python code, but also my first pull request, so I hope it all works as expected.

Here is a sample output to show some of the changes:

```
Pyrogram v1.1.13, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Delete all messages in which of the following groups:
  1. PiBot (bot)
  2. MyOtherGroup (group)
  3. get id (bot)
  4. BotFather (bot)
  5. (!) DELETE ALL YOUR MESSAGES IN ALL OF THOSE GROUPS (!)

Insert option number: 1

Deleting messages from:
PiBot

Found 29037 of your messages in "PiBot"
Offset by 10 latest messages
Searching up to the defined limit of 5000
Deleting 5000 messages (defined search limit)...

24037 messages remaining...
```

### CODE REVIEW

**Comment by hannesveit** [comment]
Disclaimer: I'm not a maintainer of this repo and so I don't have any say in whether or not this PR will be accepted or how much work will be required. But I can offer an opinion anyway ;)

After a first glance at the changeset, I think it will require some work. A few thoughts:

- Those values for `search_limit = 5000` and `offset = 10` that fit your specific use case and personal preferences aren't a good default for the constructor. I would suggest to set `search_limit = -1` by default and treat that special case in your logic, to disable a global search limit (I'd say most people don't want that, and I wouldn't want to be forced to manually change it to something like 70,000 or some other "large" number if I want to delete all of my, say, 63,293 messages). The default `offset` should be 0.
- It looks like there's a bug in there that will delete more than your `search_limit` messages. In fact, it will delete up to `self.search_limit + self.search_chunk_size - 1` messages. It's not happening in your example because in your case, `self.search_limit % self.search_chunk_size == 5000 % 1000 == 0`. If that doesn't hold, you will delete more messages than intended.
- The code also has some other (non-python-specific) issues that should be improved (naming, logic, dead code after return statement, ...)
- _"I can't test this unfortunately as I don't have any other groups."_ -- I'd say with a sweeping changeset like this, it should be the developer's responsibility to confirm that the code still works for previously supported use cases (in the absence of tests, which aren't easy to implement for something like this...). When I made my PR it was because I found an earlier PR had introduced a number of bugs because someone wanted to make it work for their specific use case but didn't test that it still works for previously supported use cases afterwards. I put quite a bit of effort into confirming that things still work as expected in all scenarios (except that, apparently, I didn't catch that search chunk sizes > 100 don't work). It's not too hard to create groups and even supergroups (public groups) and put a few messages in them.
- I agree with your concern that not filtering by `from_id=InputPeerSelf()` is likely problematic. It really needs to be tested.

@gurland are you planning to review this anytime soon? If not, or if you'd like me to do a first pass initial review, I can take a closer look.

**Comment by hannesveit** [comment]
One more question for you @jarrah31: I'm surprised to see that a `search_chunk_size` of 1000 now seems to work, when it didn't work previously (according to your bug report, it was ignored and 100 was used instead). Do you have an explanation for that?

EDIT: Ah, never mind. I found your link to the pyrogram issue and their explanation that it's actually due to pagination. That makes sense. +1 for using `search_messages` instead of `Search` in general then.

**Comment by gurland** [comment]
I think the review isn't needed in this case, I am closing this PR. Please do not pile up changes and make PRs related to only one feature/bug and for additional features please open a new Issue (gitflow-like merging style). I will update instructions in README to clarify the approval process soon.

However thanks for your research @jarrah31! You are welcome to create PR for this particular bugfix and open new Issues (and PRs) featuring `bot` peers support or`offsets`. I'd also consider taking @hannesveit's advice as they seem reasonable.

**Comment by jarrah31** [comment]
All comments are completely reasonable and make sense - as you can tell I'm no developer. :) 

@hannesveit thank you for your very useful feedback, I will certainly have a go at your suggestions.

@gurland no problems, I completely understand your reasons for closing this PR. 

Hopefully someone with actual coding skills can do a better job at implementing this! The ideas are there (bot support, search limits), it just needs to be done properly. :)

In the meantime I'll try creating a small PR for the search limit bug fix as I hopefully can't go too wrong with that.

**Comment by hannesveit** [comment]
> In the meantime I'll try creating a small PR for the search limit bug fix as I hopefully can't go too wrong with that.

I did that earlier today, it’s fixed now. But the solution isn’t ideal, as we still have the (now enforced) limitation that the `search_chunk_size` can’t be >100.

You could try to rewrite the current solution using `search_messages` instead of `Search` to remove this limitation. I’d suggest to stay as close as possible to the current implementation before moving on to other feature PRs. Maybe double-check with @gurland first.

**Comment by hannesveit** [comment]
Also, congrats on your first PR and happy to hear you were able to make this work for your use case, even though your contribution didn’t make it into the upstream repo (yet) 🙂

**Comment by jarrah31** [comment]
> I did that earlier today, it’s fixed now. But the solution isn’t ideal, as we still have the (now enforced) limitation that the `search_chunk_size` can’t be >100.

That's great, thanks! 
Yes I'd like to have a go at fixing the search messages limit because that I do have that working with the new api request, it's just that I deleted all 30,000+ messages so now need to wait for them to build up again! :) Shouldn't take too long so probably looking at next week sometime before I can test it.

**Comment by hannesveit** [comment]
I’m curious... is it really much faster with search chunk size 1000 vs 100? I’d assume it’s not a very serious limitation to find messages in chunks of 100 vs larger chunks.

**Comment by hannesveit** [comment]
@jarrah31 I just stumbled across the `search_messages` implementation in the pyrogram source code.

Not sure what you were planning to implement, but I wanted to mention that it's not worth implementing search chunk sizes > 100, because `search_messages()` _also_ uses a maximum chunk size of 100 internally: https://github.com/pyrogram/pyrogram/blob/master/pyrogram/methods/messages/search_messages.py#L168

So, while you _could_ do the manual pagination thing using `search_messages` with `limit=10000`, it won't make things faster. If anything, it'll make things slower.

FWIW, we might consider to just do a single call of `search_messages()` to find all messages at once and not bother with the raw `Search` function at all. Then again, this will _parse_ the messages, so it might be much slower than using the raw `Search` directly...

**Comment by jarrah31** [comment]
Good find, thanks @hannesveit. 

I think it’s best I leave this for now as the current 100 method search works well enough. :)

**Pull request closed without merging**
